### PR TITLE
Updates to paper wallet page

### PR DESCRIPTION
**Pull request by merland**
Updated seedpicker images after the latest changes, added some padding and a border on the images, and some text changes. 

Please don't view the border as a design suggestion for the whole site :) I was just experimenting with something to make the screenshots stand out a bit from the background.

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks @merland!

Nice touch on the CSS, any reason you wanted to do this on your images only (vs the rest of the site)?

Also, about to update with a video demo I just did live on Bitcoin Magazine.

**Comment by mflaxman** [comment]
@merland I just updated all the images to use (a modification of) your css. What do you think? I'm not good at design. Wasn't sure whether to go with `%` or `px` either.

**Comment by merland** [comment]
Great! I'm not good with design either, so I wanted to start small :)
I'm glad you took the ball and ran with it, images look much better now. Perfect example of iterative collaborative development! Would be nice to get a designer on board later on, but I don't think it is crucial right now. Good content is key.

**Comment by merland** [comment]
Found a small problem, seems to have happened when you renamed the css class. 
I fixed it, will submit in a new PR.

**Pull request merged**
