### PR TITLE
coldcard now does show zpubs

### PR DESCRIPTION
**Pull request by mmikeww**

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks @mmikeww! I could see a future where there is a universal standard here (might even be xpub instead of zpub), but for now giving both options (verify a receive address and also the xpubs themselves) is probably a goon call.

**Comment by mmikeww** [comment]
Electrum devs seem to think the standard is to use Zpubs for newer segwit addresses and xpub for legacy addresses:

https://github.com/spesmilo/electrum/issues/6946#event-4214846105

**Comment by mflaxman** [comment]
Ya, I think this is probably a poor choice on their part. For now, all the hardware wallets support it so no reason to make changes. I can see a world where new hardware wallets never adopt SLIP132 and it becomes "officially" deprecated, in which case the guide should probably recommend dropping it as well.

**Comment by mmikeww** [comment]
Well if Zpubs become deprecated, then there will be no way to generate bc1 segwit addresses in Electrum, unless they also change their software to offer the option to choose address type. For now, I think the guide will be relevant as-is for quite some time.

**Comment by mflaxman** [comment]
Electrum unfortunately has a history of digging in on standards long after others have won out. They still have Limited BIP39 Support :(

> Electrum has limited support for BIP39 and is openly considering dropping it altogether. Users cannot create BIP39 seeds, and importing them is difficult; it requires knowing to toggle hidden checkboxes and ignoring scary user prompts with inaccurate security warnings. This is confusing for hardware wallet users, as BIP39 is the universal standard that almost all hardware wallets use.

https://btcguide.github.io/known-issues/software/electrum

**Pull request merged**
