### PR TITLE
Update instructions about Keystone (formerly Cobo Vault)

### PR DESCRIPTION
**Pull request by LunaLau0**
A bunch of projects in the Bitcoin community have updated from UR1.0 to UR2.0, including Keystone (Formerly Cobo Vault).Thus, I update the related instructions on BTCguide.

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks @LunaLau0! I added one commit so the automated spellchecker would run again:
https://github.com/btcguide/btcguide.github.io/pull/94

I hope you don't mind, I didn't want to steal your git commit status but this seemed like the easiest way.

Future PRs always welcome.

**Comment by LunaLau0** [comment]
Thanks very much @mflaxman ! Never mind about the git commit. 
Furthermore, I am considering future PRs about translating the BTCguide into Chinese, which introduce this awesome guide to the Chinese community.

**Comment by mmikeww** [comment]
> have updated from UR1.0 to UR2.0

what does that stand for?

**Comment by LunaLau0** [comment]
> > have updated from UR1.0 to UR2.0
> 
> what does that stand for?

Please check this discussion for detail： https://github.com/BlockchainCommons/Airgapped-Wallet-Community/discussions/26

**Pull request closed without merging**
