### PR TITLE
update cobo-advanced with instructions for using dice

### PR DESCRIPTION
**Pull request by mmikeww**
dumb spellchecker

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks @mmikeww!

Spellchecker issues aside, I think only experts should use dice as it's harder to verify. Non-experts should use the seedpicker algorithm that Cobo already supports (not documented in the 10x guide but I'd welcome a PR to do that!). I could see having dice be an option for more advanced users though. If you know what you're doing and don't mind a ton of dice rolls, then it does save you cutting out all 2048 BIP39 words.

**Comment by mmikeww** [comment]
> Non-experts should use the seedpicker algorithm that Cobo already supports

did not know that, i will look into it

**Comment by mmikeww** [comment]
ok, pull request updated

**Comment by mflaxman** [comment]
Thanks!

Can you fix the spellchecker? Just update this file:
https://github.com/btcguide/btcguide.github.io/blob/master/.wordlist.txt

**Comment by mmikeww** [comment]
done!

**Comment by mflaxman** [comment]
Thank @mmikeww !

**Pull request merged**
