### PR TITLE
offline address exploration for coldcard

### PR DESCRIPTION
**Pull request by robot-dreams**

### CODE REVIEW

**Comment by mmikeww** [comment]
There is also this file that needs to be updated:  `known-issues/hardware/coldcard`

**Comment by mmikeww** [comment]
And this:  `https://btcguide.github.io/verify-receive-address/`

**Comment by mflaxman** [comment]
Thanks @robot-dreams!

**Comment by mflaxman** [comment]
@mmikeww A PR for those two pages would be welcome!

**Pull request merged**
