### PR TITLE
Add newline before and after lists, so that pandoc correctly detects them

### PR DESCRIPTION
**Pull request by holgern**
These changes are necessary, so that pandoc can handle lists. Without newline before a list, pandoc is not able to detect the list.

With these changes and lua filters, it is possible to create a pdf and epub from the markdown files. I will push these files as additionally PR.

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks @holgern! The newlines are good, but are the tabs intentional?

**Comment by holgern** [comment]
Yes, the tabs are needed, as otherwise pandoc does not need that the list item continue:

Example:
```
same text

* first point
* second point
     second point continues
* third point
```
We could remove the tabs, but then we need also to remove the line breaks within a item point.

**Comment by mflaxman** [comment]
Oof, another merged PR created merge conflicts :(

> We could remove the tabs, but then we need also to remove the line breaks within a item point.

Removing line breaks within item points sounds like the best approach, can you do that? Lots of people coming in with PRs have no idea how jekyll/MD work, so the easier we can make their PRs the better.

Sorry for the delay in responding to these, I've been busy this past week but it's no excuse. Love the contributions and want to keep pushing this guide forward.

**Comment by holgern** [comment]
I resolved the conflict and removed line breaks within a list point.

**Comment by mflaxman** [comment]
This looks great, thanks @holgern!

**Pull request merged**
