### PR TITLE
updated seedpicker image (now with QR button), updated seedpicker link

### PR DESCRIPTION
**Pull request by merland**

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks! Any reason you didn't update the copy to recommend using the QR code? NBD, I can always add that later.

**Comment by merland** [comment]
The only reason was lack of time :)
I can do the copy updates too, just not sure when.

**Comment by mflaxman** [comment]
No pressure, your PRs are always very much appreciated :)

**Comment by merland** [comment]
Where do you want to go with those instructions, regarding qr scan vs file download? My choice would probably be to give detailed instructions for the qr scanning case and shorter less detailed for the file download. What do you think @mflaxman?

**Comment by mflaxman** [comment]
Maybe default instructions are QR code (because it's easier), but the advanced section is file download.

It's a little tricky because proper QR code setup implies you have multiple computers (and this is done on your airgap computer), whereas file download could all take place on the same computer (that is then wiped). Of course there are lots of permutations and it could be something in between; perhaps you print out your QR code and then wipe the computer without saving the file.

**Comment by merland** [comment]
> Maybe default instructions are QR code (because it's easier), but the advanced section is file download?

Sounds good. I have started with this but I may not be able to create the PR until Monday.
I don't want to tweet about QR support until there are good (OK, at least) instructions :)

**Comment by merland** [comment]
>  I have started with this 

I realize now I may not be the best person to create the first iteration of the QR instructions... Should we keep the dry-run part? And how much to include in the dry-run? Even the import to Specter? I guess I don't fully understand the rationale of the dry-run or how to best stitch it together with the rest of the instructions.

**Comment by mflaxman** [comment]
I'm thinking for dry-run the best choice is to add a note telling people to try everything on testnet (see #21). If you've done that, you don't need a dry-run.

I know many/most people will ignore this instruction and some of them will lose funds. There's only so much you can do to protect people from themselves though :(

**Pull request merged**
